services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "13"
      CPU_CORES: "4"
      RAM_SIZE: "12G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./shared:/data
    restart: always
    stop_grace_period: 2m